components:
  path: kubeflow/components
  components:
    - name: my_add
    - name: my_divide

pipelines:
  path: kubeflow/pipeline
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6Im9jZGt1YmUiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUsb3BlcmF0b3IiLCJkZXBsb3kiOmZhbHNlLCJleHAiOjQ4NjY5NTA2NTEsImlhdCI6MTYyNjk1MDY1MSwiaXNzIjoiRGt1YmUifQ.hm40HelIm3VPf7c9SRpDSZEK7U1t7HLpY8IO36yNLaXf8xRke8CuEWw3dJmlgkyHabBALpn7U6_qYSMQI2Tn-6L0bx_Rb_460H2jEhg1IKH6UCLVB9xLdgOnbtzcrJl5pJw3VI2jkJJ0hVdMPFyZU35W7QHVVFDesHm-J1Du6dmhtxcUeWvFBo5J-LDEsQ-R6l4sf5XNDr8aPvonbrR0ejiwNhTaaQRLkmcXnxSfqLaLMiIdrWYE5gkVaFODWmBpIWHIXpHf3BmNNavzWvsvYowyTvmyhAmIh2ncMcP9tQmR65ddc0-LOOaVBxF0_zXnFuutcYaGUqp0W8lq2AOcCg
  pipelines:
    - name: workflow.py
      run: true
