conda_env:
  path: jobs/conda_env.yaml

#docker_envs:
   #- ocdr/custom-training:latest

#Dockerfile: Dockerfile

#components:
 # path: kubeflow/components
  #components:
   # - name: my_add
    #- name: my_divide

#pipelines:
 # path: kubeflow/pipeline
  #token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6Im9jZGt1YmUiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUsb3BlcmF0b3IiLCJkZXBsb3kiOmZhbHNlLCJleHAiOjQ4NjczNjE4MTYsImlhdCI6MTYyNzM2MTgxNiwiaXNzIjoiRGt1YmUifQ.n1kI-9Bn3fIWgluap9V6DyAXTkiYI5QNNWVD5cZN4ZSc57q_lIi-Ggk_3235_e7AmyZrUSEyGhd0WQ8JEgSL74I8aYPjLBso81fjsTfncNHA1iR09qpk_R9jUvl5gwhgABkvpsjU04bI5SYCZymR2MNh7zcn8XrTzs_YN9Ih0Lkf3z60TFP8bKIgIo0865SfkoqZRU2PJ1vTNOAw4sxBu-M-RP63Cueva8ZGLEt8kKGSw15H1QuK5JCzIxhJowRFylaFFCgAFaQEc0QIeKZufJBiCkOTsn9pNDXvev0LIVtPoJ3Ae9qqvs2KmtCHQh3S7An6K59DPKc9iixaRkLrUQ 
  #pipelines:
   # - name: workflow.py
    #  run: true

#jobs:
 # path: jobs
 # jobs:
  #  - name: train.yaml
   #   run: true
