name: mn
token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6Im9jZGt1YmUiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUsb3BlcmF0b3IiLCJleHAiOjQ4ODQ5MTc2OTAsImlhdCI6MTY0NDkxNzY5MCwiaXNzIjoiREt1YmUifQ.fxzWtAJNx5wujREnNUP2zHSbbZvC-dyJM-q5PJ86-XOrqReJpj0bJzzl4f31ulFGkjVbJ1RYa0l3ytKnbrvCk-Zz4HakEtW53hGqa_evZz6TLcvr7CGhJISlKWjEYL8ODwWG36ipoVrC1NFYq33wM9Sj-CUydWtV9WSk9WbV9vbmcoXA3bHILcEf0s5pJxKnwhYdh7GaBNzN_KOqnpaOD5uH0n7Bf9pMW0buMXpr5WcKOi4U6GDQagYURLr8tophSsmqLznge4j0TJhOhuQ9mYFqx2vEYjb6mzfXngb-RVZmWBkquTg1bOssJEYvdEWD0vCaoz-dM8TZv5MZ_SS3Sw
user: ocdkube
parameters:
  class: training
  training:
    executor:
      choice: dkube
      buildfromproject: false
      dkube:
        framework:
          choice: tensorflow
          details:
            version: 2.0.0
            image: 'ocdr/dkube-datascience-tf-cpu:v2.0.0-9'
    datums:
      workspace:
        data:
          name: 'ocdkube:mn'
          version: ''
        script: python mnist/train.py
      datasets:
        - name: 'ocdkube:mn'
          mountpath: /mnist
      outputs:
        - name: 'ocdkube:mn'
          mountpath: /model
    featuresets: {}
    tags: []
    hyperparams:
      customkv:
        - key: EPOCHS
          value: '1'
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
