name: testing
token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6Im9jZGt1YmUiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUsb3BlcmF0b3IiLCJkZXBsb3kiOmZhbHNlLCJleHAiOjQ4NjcxMDYwMjcsImlhdCI6MTYyNzEwNjAyNywiaXNzIjoiRGt1YmUifQ.e-WHUOdsh9h_RBOQ9RHPNJmkvQjQAJz4nS9uix5HJMltmjKlLtnQfqgtWrsgFImAyx4RTK_WYxRf6M2lA5SehOX84p3IDkMdc-bsPF0XrOnD1bug_mPcWVU87AlYFaqcYbiEx1h38cAPADMnCus6MRoVzYlQOV_vu_45BEVDFiyKQ9ypJ0IdiDilZN7bCYOkbUzE5uEKFq6-Sl2gO0okLKzHZVkZG2EoBrNuidEL_sry0-hIiGc1zpvhzcKMDElryu8OzuM-zB3pMwxVcTkAXvGpAvUNkUxVD8ZbTdZu-CPmEWnM8tCX6jj-ttIEATy-je3X0yRMlxvLYuIdZ0KPDQ
parameters:
  class: training
  training:
    executor:
      choice: dkube
      dkube:
        framework:
          choice: tensorflow
          details:
            version: '2.0.0'
            image: ocdr/dkube-datascience-tf-cpu:v2.0.0-5
    datums:
      workspace:
        data:
          name: ocdkube:cicd-public
          version: master
        script: cd tf/classification/mnist/digits/classifier/program-2.x; python model.py
      datasets:
      - name: ocdkube:mn
        mountpath: "/opt/dkube/input"
      outputs:
      - name: ocdkube:mn
        mountpath: "/opt/dkube/output"
    hyperparams:
      customkv: []
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    tags: []
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
