name: testing
token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6InNhcmF0aGRhc2FyaSIsInJvbGUiOiJkYXRhc2NpZW50aXN0LG1sZSxwZSIsImRlcGxveSI6ZmFsc2UsImV4cCI6NDg3MjcyODQ2NiwiaWF0IjoxNjMyNzI4NDY2LCJpc3MiOiJEa3ViZSJ9.3Lnb_mR369KqE0TkH-7tDDoeeme-QQhsiKsmr5JhIBU9rMfTpqRVIMM515sIjgxizaEZYKO5dw111hh3k_ftMsz-5bm4oT8yiaJRYEd9jskofxBLAC7Ebh6EsNXy-XvoFELTg3Mcc_t2z3TP7bIj8lKp0H_hCArIeaTdLxo7rplWx0RROSzIM2YsFDlXMKK8lj83q2BDUNM_WGSBxAZaOYk4Ar5wO9ATTMG6wTNGSoz_4oGqxD8R-LU4krF6wQ1gl7iMCcgEL4FhisecTIcObP6W6z3gtvWyV_zPT8oQU0Tp3F69L__rwEYkZ2lobP1azPxx8YJnj93qHVtp0OBoFA
parameters:
  class: training
  training:
    executor:
      choice: dkube
      dkube:
        framework:
          choice: tensorflow
          details:
            version: '2.0.0'
            image: ocdr/dkube-datascience-tf-cpu:v2.0.0-6
    datums:
      workspace:
        data:
          name: sarathdasari:test
          version: master
        script: cd tf/classification/mnist/digits/classifier/program-2.x; python model.py
      datasets:
      - name: sarathdasari:test
        mountpath: "/opt/dkube/input"
      outputs:
      - name: sarathdasari:test
        mountpath: "/opt/dkube/output"
    hyperparams:
      customkv: []
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    tags: []
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
