name: mnist
user: sarathdasari
parameters:
  class: training
  training:
    executor:
      choice: dkube
      buildfromproject: false
      dkube:
        framework:
          choice: tensorflow
          details:
            version: 2.0.0
            image: 'ocdr/dkube-datascience-tf-cpu:v2.0.0-6'
    datums:
      workspace:
        data:
          name: 'ocdkube:tf-example-0251285494'
          version: ''
        script: python mnist/train.py
      datasets:
        - name: 'ocdkube:mnist'
          mountpath: /mnist
      outputs:
        - name: 'ocdkube:mnist'
          mountpath: /model
    featuresets: {}
    tags: []
    hyperparams:
      customkv:
        - key: EPOCHS
          value: '1'
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
