name: training
user: sarathdasari
token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6InNhcmF0aGRhc2FyaSIsInJvbGUiOiJkYXRhc2NpZW50aXN0LG1sZSxwZSIsImRlcGxveSI6ZmFsc2UsImV4cCI6NDg3MjgwODE0MSwiaWF0IjoxNjMyODA4MTQxLCJpc3MiOiJEa3ViZSJ9.oPghGU9NjUcgG1CRQT_f1d9qKchKda6r7Ls7iPjuLyeq_bH-czK10Mj-sYwYyjGVPpUXyEpGfJmawT1ZEvfn4U0L-uLX70JMBWuJ0ZPVTuGVKOB8D_rsK7gkdzsgBw8ZPzL53aj7JAX0AWufCjMXW64DIJPzoGqqQe-wFXrJmbgjEVIB7igG6A1xStdzigWo70kx_GimX8wcdnZnsoYEh3EXLI_RVNXm6PypqRIT-BUvqUALOV-zOGOjPZAW1hX7L_gc0NAk18L_esk6UQHm2JKdE0cGsndRhV1TbUYmoDHORdCMBGdo0oIJbJRFaxlfVE8lTZ24aikKUxtLsGiA2w
parameters:
  class: training
  training:
    executor:
      choice: dkube
      dkube:
        framework:
          choice: tensorflow
          details:
            version: '2.0.0'
            image: ocdr/dkube-datascience-tf-cpu:v2.0.0-6
    datums:
      workspace:
        data:
          name: sarathdasari:mn-1
          version: master
        script: cd tf/classification/mnist/digits/classifier/program-2.x; python model.py
      datasets:
      - name: sarathdasari:mn-1
        mountpath: "/opt/dkube/input"
      outputs:
      - name: sarathdasari:mn-1
        mountpath: "/opt/dkube/output"
    hyperparams:
      customkv: []
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    tags: []
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
