name: testing
token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6Im9jZGt1YmUiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUsb3BlcmF0b3IiLCJkZXBsb3kiOmZhbHNlLCJleHAiOjQ4NjYxOTYwNTAsImlhdCI6MTYyNjE5NjA1MCwiaXNzIjoiRGt1YmUifQ.7AKFfzuCscgtZHEIN2WJNE7ZsLJohXvN4hhBJafnexI7HL7oPYdf_amXvZ1K9ASfK7RWqdrK0Z-oCVUw2hjbaVNaLDHZVbxjsH-hWyZkxQ_w1ZGcbSHavt6HudivMfaZaDElDAuPmtGWJiIiIv3R-sxV6TesvUqnpF-JbxnMIoaezWckTjIAX14v0-7FF3Texe-uvimtQtuO_FZzESDwqiznYOfCqGDZ7Vg3hJh8RM2JSKUBrVx2UhXrbs_f3Pml6UZkzpWglUigHMbjyejyWRcPZZk3bnEaUMuzB22Bk7ybYXpUrnJY7jDzLcmLLfya8gpvhKDmXKAQnjV238GV-Q
parameters:
  class: training
  training:
    executor:
      choice: dkube
      dkube:
        framework:
          choice: tensorflow
          details:
            version: '1.14'
            image: ocdr/d3-datascience-tf-cpu:v1.14-5
    datums:
      workspace:
        data:
          name: ocdkube:mnist
          version: master
        script: python model.py
      datasets:
      - name: ocdkube:mnist
        mountpath: "/opt/dkube/input"
      outputs:
      - name: ocdkube:mnist
        mountpath: "/opt/dkube/output"
    hyperparams:
      customkv: []
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    tags: []
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
